version: '3'
services:
  mysql8:
    image: mysql:8.0.21
    container_name: mysql8_docker
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: test
      MYSQL_USER: mysql
      MYSQL_PASSWORD: password
      TZ: 'JST'
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    volumes:
    - ./docker/mysql8/data:/var/lib/mysql
    - ./docker/mysql8/my.cnf:/etc/mysql/conf.d/my.cnf
    - ./docker/mysql8/sql:/docker-entrypoint-initdb.d
    ports:
    - 3306:3306
